[build]
  command = "cd frontend/app && npm install && npm run build"
  publish = "frontend/app/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
